### ISSUE TITLE
compile error with WiFiRM04 & Arduino1.6.5

### ISSUE THREAD

**Issue by ygking** [chunlinhan/WiFiRM04#32]
Getting the build fail with below error:

Arduino: 1.6.5 (Windows 7), Board: "Arduino Uno"
Sketch uses 30,096 bytes (93%) of program storage space. Maximum is 32,256 bytes.
Global variables use 3,175 bytes (155%) of dynamic memory, leaving -1,127 bytes for local variables. Maximum is 2,048 bytes.
processing.app.debug.RunnerException: Not enough memory; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing your footprint.
    at processing.app.debug.Compiler.size(Compiler.java:343)
    at processing.app.debug.Compiler.build(Compiler.java:122)
    at processing.app.Sketch.build(Sketch.java:1109)
    at processing.app.Sketch.build(Sketch.java:1084)
    at processing.app.Editor$BuildHandler.run(Editor.java:1955)
    at java.lang.Thread.run(Thread.java:745)
Not enough memory; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing your footprint.
  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

It seems that no enough dynamic memory to use which exceed 2048 size. Do you have any idea about this error?

**Comment by chunlinhan** [comment]
Hi ygking,

Remove "#define _DEBUG_" in "at_drv.cpp" would help.
